### ISSUE TITLE
Create repository

### ISSUE THREAD

**Issue by LuisHsu** [WasmVM/wasi-node#1]
Add .gitignore, src folder....

**Comment by kevinbird61** [comment]
Or some building tool suggestions

**Comment by LuisHsu** [comment]
Building tool suggestions?

**Comment by kevinbird61** [comment]
Got it, we use `node-gyp` to build our project.

**Comment by LuisHsu** [comment]
Essential files are all created, everyone can follow the dummy `fd_prestat_get` to start development.
